### ISSUE TITLE
Not able to create response token

### ISSUE THREAD

**Issue by Venkat2050** [suresh-n/sasonline_python_auth#1]
HI Suresh,

Thanks for the code.

I ran the code in eclipse, able to  generate authorization URL. when I opened the URL in chrome, SASonline  web page opened and I gave my credentials after that it show 

" This site can’t be reached 127.0.0.1 refused to connect.
Try:
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED
 
I checked my LAN  connection, proxy is already disabled and firewall is also disabled for chrome.

any idea on this issue.

thanks,
Venkat

**Comment by suresh-n** [comment]
Hi Venkat, 
this is actually a workaround, i was unable to find the way to create a token using the oauth post method. so i created this script.  the script is still in progress i have to fetch the auth URL.


you can try this , create separate file,  paste the auth response URL then try running script you must get the token you can use that to call the api.

authorization_response = 'paste the the auth reponse code'
token_endpoint = 'https://alphaapi.sasonline.in/oauth2/token'
token = client.fetch_token(token_endpoint, authorization_response=authorization_response)
print(token)
