### ISSUE TITLE
TOTP login

### ISSUE THREAD

**Issue by mehtakrunal19** [suresh-n/sasonline_python_auth#2]
Will this work with new TTP login? Can you please help with the new TOTP login?

**Comment by suresh-n** [comment]
No. Using below method you can generate otp.

import pyotp

factor2 = pyotp.TOTP('E34I3P2S222E4OP4GL4645I5H5327B5P').now() 

Thanks

**Comment by mehtakrunal19** [comment]
Yes I got that sorted but how to integrate that into main code to login automatically? Sorry it might be lame question but not an expert on this .. not even from coding background

**Comment by suresh-n** [comment]
are you using python or nodejs ? 

I still did not tested sasonline login with totp. tomorrow i will try and share the code snippet here.

**Comment by mehtakrunal19** [comment]
I am using python.   
Super .thanks a lot for your time and prompt response .. appreciate a lot...

**Comment by mehtakrunal19** [comment]
By the way I am using this
https://github.com/algo2t/alphatrade

**Comment by suresh-n** [comment]
yeah look like this repo not updated for the totp to work. its hard we cannot see much details in sasonline support page as well any official API.

**Comment by suresh-n** [comment]
totp also method also works.
