### ISSUE TITLE
The OAuth2 request resulted in an error

### ISSUE THREAD

**Issue by bhaskarndas** [suresh-n/sasonline_python_auth#3]
Hi when I run auth_generate_response.py file it throws the following error

The OAuth2 request resulted in an error.

Error: invalid_client
Description: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)
Hint: The requested OAuth 2.0 Client does not exist.
Debug:
You are seeing this default error page because the administrator has not set a dedicated error URL (environment variable OAUTH2_ERROR_URL is not set). If you are an administrator, please read [the guide](https://www.ory.sh/docs) to understand what you need to do. If you are a user, please contact the administrator.

**Comment by suresh-n** [comment]
client_id = 'SAS-CLIENT' must wrong please work with Sasonline support to make it work.

**Comment by bhaskarndas** [comment]
I am giving my client id. It's sad they are not providing any kind of support on their APIs. I believe client_id = my id?

**Comment by bhaskarndas** [comment]
Thanks for your client_id. Sasonline had given me wrong id and they refused to provide any further support. The code is working now. Thanks once again for your code.
